version: '3.9'

services:
  nginx:
    volumes:
      - ./nginx/local.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "3000:80"

  backend:
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://:${REDIS_PASSWORD:-redissecret}@redis:6379
      - MONGO_URI=mongodb://${MONGO_ROOT_USER:-admin}:${MONGO_ROOT_PASSWORD:-mkapp_secret_2026}@mongo:27017/mk-app?authSource=admin

  frontend:
    build:
      args:
        - REACT_APP_API_URL=/api/v1
        - REACT_APP_SOCKET_URL=/
