apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mk-app-production

resources:
  - ../../base

patchesStrategicMerge:
  - patch-replicas.yaml
  - patch-resources.yaml
  - patch-env.yaml

images:
  - name: mk-backend
    newName: gcr.io/mk-app/backend
    newTag: latest
  - name: mk-frontend
    newName: gcr.io/mk-app/frontend
    newTag: latest
